"""Constants for integration"""
DOMAIN = "helios2n"
ATTR_METHOD = "method"
DEFAULT_METHOD = "GET"
ATTR_ENDPOINT = "endpoint"
ATTR_TIMEOUT = "timeout"
DEFAULT_TIMEOUT = 10
ATTR_DATA = "data"
ATTR_JSON = "json"
ATTR_ENTRY = "entry"
CONF_CERTIFICATE_FINGERPRINT = "certificate_fingerprint"
DEFAULT_VERIFY_SSL = True
SERVICE_RECAPTURE_CERTIFICATE = "recapture_certificate"
ATTR_CERT_MISMATCH = "certificate_mismatch"