name: HACS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  hacs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: HACS validation
        uses: hacs/action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          category: integration
          comment: true
